/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: sanity\schema.json
export type Comment = {
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  comment?: string;
  article?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "article";
  };
  approved?: boolean;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    _type: "image";
  };
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  audioUrl?: string;
  publishedAt?: string;
  comments?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "comment";
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Comment
  | Category
  | Slug
  | Article
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity\queries\articles.ts
// Variable: ARTICLE_BY_SLUG_QUERY
// Query: *[_type == "article" && slug.current == $slug][0] {    _id,    title,    publishedAt,    "slug": slug.current,    "author":author-> {      name,      "slug": slug.current    },    "mainImage": mainImage.asset->url,    "category": categories[0]-> {    name,     "slug": slug.current,    },    content,  }
export type ARTICLE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  publishedAt: string | null;
  slug: string | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
  mainImage: string | null;
  category: {
    name: string | null;
    slug: string | null;
  } | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: sanity\queries\articles.ts
// Variable: ALL_ARTICLES_QUERY
// Query: *[_type == "article"] | order(publishedAt desc) [$start...$end] {    _id,    title,    publishedAt,    "slug": slug.current,    "author":author->{      name,      "slug": slug.current,    },    "mainImage": mainImage.asset->url,     "excerpt": pt::text(      content[_type == "block"][0...1]    ),    "category": categories[0]-> {      name,      "slug": slug.current      },  }
export type ALL_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  publishedAt: string | null;
  slug: string | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
  mainImage: string | null;
  excerpt: string;
  category: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity\queries\articles.ts
// Variable: TOTAL_ARTICLES_COUNT
// Query: count(*[_type == "article"])
export type TOTAL_ARTICLES_COUNT_RESULT = number;

// Source: sanity\queries\articles.ts
// Variable: ARTICLES_BY_CATEGORY_QUERY
// Query: *[_type == "article" && $slug in categories[]->slug.current] | order(publishedAt desc) [$start...$end] {    _id,    title,    publishedAt,    "slug": slug.current,    "author": author-> {       name,      "slug": slug.current,    },    "mainImage": mainImage.asset->url,    "category": categories[0]->{       name,      "slug": slug.current,    },     "excerpt": pt::text(      content[_type == "block"][0...1]    ),  }
export type ARTICLES_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  publishedAt: string | null;
  slug: string | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
  mainImage: string | null;
  category: {
    name: string | null;
    slug: string | null;
  } | null;
  excerpt: string;
}>;

// Source: sanity\queries\categories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(name asc) {    _id,    name,    "slug": slug.current,    description  }
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
}>;

// Source: sanity\queries\categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    description  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
} | null;

// Source: sanity\queries\categories.ts
// Variable: TOTAL_CATEGORY_COUNT
// Query: count(*[_type == "article" && $slug in categories[]->slug.current])
export type TOTAL_CATEGORY_COUNT_RESULT = number;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "article" && slug.current == $slug][0] {\n    _id,\n    title,\n    publishedAt,\n    "slug": slug.current,\n    "author":author-> {\n      name,\n      "slug": slug.current\n    },\n    "mainImage": mainImage.asset->url,\n    "category": categories[0]-> {\n    name, \n    "slug": slug.current,\n    },\n    content,\n  }\n': ARTICLE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "article"] | order(publishedAt desc) [$start...$end] {\n    _id,\n    title,\n    publishedAt,\n    "slug": slug.current,\n    "author":author->{\n      name,\n      "slug": slug.current,\n    },\n    "mainImage": mainImage.asset->url, \n    "excerpt": pt::text(\n      content[_type == "block"][0...1]\n    ),\n    "category": categories[0]-> {\n      name,\n      "slug": slug.current\n      },\n  }\n': ALL_ARTICLES_QUERY_RESULT;
    'count(*[_type == "article"])': TOTAL_ARTICLES_COUNT_RESULT;
    '\n  *[_type == "article" && $slug in categories[]->slug.current] | order(publishedAt desc) [$start...$end] {\n    _id,\n    title,\n    publishedAt,\n    "slug": slug.current,\n    "author": author-> { \n      name,\n      "slug": slug.current,\n    },\n    "mainImage": mainImage.asset->url,\n    "category": categories[0]->{ \n      name,\n      "slug": slug.current,\n    }, \n    "excerpt": pt::text(\n      content[_type == "block"][0...1]\n    ),\n  }\n': ARTICLES_BY_CATEGORY_QUERY_RESULT;
    '\n  *[_type == "category"] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    description\n  }\n': ALL_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    description\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  count(*[_type == "article" && $slug in categories[]->slug.current])\n': TOTAL_CATEGORY_COUNT_RESULT;
  }
}
